config/routes.rb
Rails.application.routes.draw do
  root "welcome#home"
  resources :articles
  get 'welcome/home' ,to: 'welcome#home'
  get 'signup', to: 'users#new'
  resources :users , exept:[:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
	belongs_to :user
  validates :title, presence: true, length: {minimum: 4,maximum: 500 }
  validates :description, presence: true, length: {minimum: 10,maximum: 1000}
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base 
	has_many :articles, dependent: :destroy
	before_save {self.email = email.downcase}
	validates :username , presence: true,uniqueness: {case_sensitive: false}, length: {minimum: 4,maximum: 25}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 100},
				uniqueness: {case_sensitive: false},
				format: {with: VALID_EMAIL_REGEX}
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :loged_in? 
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def loged_in?
  	!!current_user
  end

  def require_user
  	if !loged_in?
  		flash[:danger] = "You must Loged in to perfome this action"
  		redirect_to root_path
  	end
  	
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_params, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit,:update,:destroy]
  def index
      @article = Article.paginate(page: params[:page],per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
     @article = Article.new(article_params)
      @article.user = current_user
    if @article.save
       flash[:success] = "Artciles created Succesfully"
      redirect_to article_path(@article)
      else
      render 'new'
    end

    def update
      if @article.update(article_params)
        flash[:success] = "Articles updated Succesfully"
        redirect_to article_path(@article)
        else
        render 'edit'
      end
    end

    def show
    end

    def destroy
      @article.destroy
      flash[:danger] = "Articles succesfully Destroyed "
       redirect_to articles_path
    end


  end

  private
  def set_params
     @article = Article.find(params[:id])
  end


  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user and !current_user.admin?
        flash[:danger] = "You can edit your own articles"
        redirect_to root_path      
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		
	end

	def create
		user =User.find_by(email: params[:session][:email])
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:success] = "You have been Succesfully Loged In"
			redirect_to user_path(user)
		else
			flash.now[:danger] = "Problem with User Information"
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "You have succesfully loged out"
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update, :show]
	before_action :require_own_user, only: [:edit, :update, :destroy]
	before_action :require_admin, only: [:destroy]

	def new
		@user = User.new
	end

	def index
		@users = User.paginate(page: params[:page], per_page: 3)
	end
	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id]= @user.id
			flash[:success] = "Welcome to the alpha blog #{@user.username}"
			redirect_to user_path(@user)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @user.update(user_params)
			flash[:success] = "Account updated Succesfully"
			redirect_to articles_path
		else
			render 'edit'
		end
	end

	def show
		@user_articles = @user.articles.paginate(page: params[:page], per_page: 3)

	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:danger] = "Article and User destroy Succesfully"
		redirect_to root_path
	end

	private
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

	def set_user
		@user = User.find(params[:id])
	end

	def require_own_user
		if current_user!= @user and !current_user.admin?
			flash[:danger] = "Dont try to be Over-Smart"
			redirect_to root_path			
		end
	end

	def require_admin
		if !current_user.admin and loged_in?
			flash[:danger] = "Only admin can perform this action"
			redirect_to root_path
		end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def home
		redirect_to articles_path if loged_in?
		@disable_nav = true
	end
	
	def landing_page
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user)
		gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
		gravatar_url = "https://www.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url,alt: user.username, class: "img-circle resposive")
	end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
<div class="row">
   <div class="col-xs-8 col-xs-offset-2">
     <h4><%= link_to  article.title, article_path(article) %></h4>
    <blockquote class="bs-callout-danger">
      <p><%= truncate(article.description,length: 700) %> Created By: <small><%= article.user.username if article.user %> , <%= time_ago_in_words(article.created_at) %> ago , last updated at <%= time_ago_in_words(article.updated_at,include_seconds: true)%> </small></p>

    </blockquote>
    <% if loged_in? && (current_user == article.user || current_user.admin?) %>
    <%= link_to "Edit this artcle",edit_article_path(article), class:"btn btn-xs btn-primary" %>
    <%= link_to "Delete this artcle",article_path(article), method: :delete,data: { confirm: "Are you shure you want to delete?" },class: "btn btn-xs btn-danger" %>
    <% end %>
  </div>
</div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors',obj: @article %>

<div class="row">
  <div class="col-sm-12">
    <%= form_for(@article,:html=>{class: "form-horizontal", role: "form"}) do |f| %>
       <div class="form-group">
         <div class= "control-label col-xs-2">
            <%= f.label :title %>
         </div>
         <div class="col-xs-10">
            <%= f.text_field :title, class: "form-control",placeholder: "Title for Article",autofocus: true %>
         </div>
     <div>
    

        <div class="form-group">
           <div class= "control-label col-xs-2">
          <%= f.label :description%>
           </div>
           <div class="col-xs-10">
              <%= f.text_area :description, rows:8 ,class: "form-control",placeholder: "Body for Article",autofocus: true %>
           </div>
       </div>
          <div class="form-group">
            <div class="col-xs-offset-2 col-xs-10">
            <%= f.submit nil,class: "btn btn-primary btn-lg"%>
             </div>
          </div>
    <% end %>
       <div class="text-center">
          <p><%=link_to "Back to Listing Articles" ,articles_path,class:"btn" %></p>
       </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center">Edit new Form</h1>
<%= render 'form'%>

app/views/articles/index.html.erb
<h1 class="text-center">Listing Article</h1>
<%= render 'article',obj: @article %>
<div class="text-center">
	<%= will_paginate @article %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center">Creating Aplication</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="container">
	<h4 class="text-center">Showing selected article</h4>
	<div class="well well-lg col-xs-offset-3 col-xs-6">
	<h4><strong><%= @article.title %></strong></h4>
	<p><%= @article.description %></p>
		<%=link_to "View all articles" ,articles_path ,class:"btn btn-xs btn-success"%>
	<% if loged_in? && (current_user == @article.user || current_user.admin?) %>
	<%= link_to "Edit this artcle",edit_article_path(@article), class:"btn btn-xs btn-primary" %>
	<%= link_to "Delete this artcle",article_path(@article), method: :delete,data: { confirm: "Are you shure you want to delete?" },class: "btn btn-xs btn-danger" %>
		<% end %>
</div>

app/views/layouts/_footer.html.erb
<!--
<div class="container col-sm-12 footer-blog">
  <footer class="text-center footer-content">
    <div class="row">
      <ul>
        <li></li>
      </ul>
    </div>
    <small>Copyright &copy; https://www.sagar.com</small>
  </footer>
</div>
-->
  <footer class="footer">
      <div class="container">
        <p class="text-center">@copyright www.NewsMap.com</p>
      </div>
  </footer>

app/views/layouts/_messges.html.erb
<div class="row">
  <div class="col-xs-offset-2 col-xs-8 ">
    <% flash.each do |name , msg|%>
       <div class='alert alert-<%="#{name}"%>'>
         <a herf="#" class="close" data-dismiss="alert">&#215;</a>
         <%= content_tag :div,msg,:id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
      <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
   <!-- Collect the nav links, forms, and other content for toggling -->
<nav class="navbar navbar-default ">
  <div class="container">
  <div class="navbar-header">
      <%= link_to "News Map" ,root_path,class:"navbar-brand"%>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Articles" ,articles_path%></li>
            <li><%= link_to "Users", users_path%> </li>
            <li><%= link_to 'Add new Article',new_article_path %></li>
      <ul class="nav navbar-nav ">
          <!--Log in -->
            <!--Log out -->
            <%if loged_in? %>
           <li><%= link_to "Logout", logout_path, method: :delete %><%= p "(*Admin)" if current_user.admin? %> </li>
            <% else%>
              <li><%= link_to "Login", login_path %></li>
              <li><%= link_to "Sign Up", signup_path%></li>
            <% end %>
      </ul>
      </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewM</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' unless @disable_nav %>
  
  <%= yield %>
   <%= render 'layouts/footer' unless @disable_nav %>
  <!--
  <%#=  debug(params) if Rails.env.development?  %>-->
</body>
</html>

app/views/shared/_errors.html.erb
<%if  obj.errors.any?  %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
          <%= pluralize(obj.errors.count,"error") %>
          Prohibitted from Saving Article:
        </h2>
      </div>
        <div class="panel-body">
          <ul>
              <% obj.errors.full_messages.each do |msg|%>
              <li><%= msg %></li>
              <% end %>
          </ul>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors',obj: @user %>

<div class="row">
  <div class="col-sm-12">
    <%= form_for(@user,:html=>{class: "form-horizontal", role: "form"}) do |f| %>
     	    <div class="form-group">
           <div class= "control-label col-xs-3">
          <%= f.label :username%>
           </div>
           <div class="col-xs-9">
              <%= f.text_field :username,class: "form-control",placeholder: "Enter a Username",autofocus: true %>
           </div>
         </div>
        <div class="form-group">
           <div class= "control-label col-xs-3">
          <%= f.label :email%>
           </div>
           <div class="col-xs-9">
              <%= f.email_field :email,class: "form-control",placeholder: "Enter a email",autofocus: true %>
           </div>
         </div>
         <div class="form-group">
           <div class= "control-label col-xs-3">
          <%= f.label :password%>
           </div>
           <div class="col-xs-9">
              <%= f.password_field :password,class: "form-control",placeholder: "Enter a password",autofocus: true %>
           </div>
          </div> 
          <div class="form-group">
            <div class="col-xs-offset-3 col-xs-9">
            <%= f.submit(@user.new_record? ? "Sign Up": "Update Account",class: "btn btn-primary btn-lg")%>
             </div>
          </div>
    <% end %>
       <div class="text-center">
          <p><%=link_to "Back to Listing Articles" ,articles_path,class:"btn" %></p>
       </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center">Edit Your account</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center"> NewsMap Blog Users</h1>
<% @users.each do |user|%>
	<ul>
		<div class="row">
			<div class="col-md-offset-4 col-md-3">
				<div class="well text-center">
					<li><%= link_to gravatar_for(user), user_path(user)%></li>	
					<li><%= link_to user.username, user_path(user)%>
					</li>
					<li><small></small><span class="badge"><%= pluralize(user.articles.count , "article") if user.articles %></span></li>
					<% if loged_in? and current_user.admin? %>
					<li>
					<%= link_to "Delete this user", user_path(user) ,method: :delete, data: {confirm: "Do you Want to Delete this user?"} %>
						
					</li>
					<% end %>
				</div>		
			</div>
		</div>
	</ul>	
<% end -%>
	<div class="text-center">
		<%= will_paginate @user%>
	</div>	

app/views/users/new.html.erb
<h1 class="text-center">Sign up to Alpha Bolg</h1>
<div class="col-xs-offset-3 col-xs-6 col-xs-offset-3">
	<%= render 'form' %>
</div>

app/views/users/show.html.erb
<h1 class="text-center"> Welcome to <%= @user.username %>'s profile</h1>
<div class="row">
	<div class="col-md-offset-4 col-md-3 text-center">
		<div class="well">
		<li><%= gravatar_for(@user) %></li>
		<h3 class="text-center"> Articles of <%= @user.username %></h3>
		</div>
	</div>
</div>

<%= render 'articles/article',obj: @user_articles %>
<div class="text=center col-md-offset-4">
	<%= will_paginate @user_articles %>
</div>

app/views/welcome/home.html.erb
<div class="col-xs-3 part1">
      <div class="container">
        <h3>News Map</h3>

        <div class="col-xs-3">
        <!--
        <ul class="list-group">
          <li><%= link_to "Articles" ,articles_path , class: 'list-group-item'%></li>
            <li><%= link_to "Users", users_path, class: 'list-group-item'%> </li>
            <li><%= link_to 'Add new Article',new_article_path, class: 'list-group-item' %></li>
            <%if loged_in? %>
            <li><%= link_to "Logout", logout_path, method: :delete, class: 'list-group-item' %></li>
            <li class="dropdown , class: 'list-group-item'">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <%= "(*Admin)" if current_user.admin? %> <span class="caret"></span></a>
            </li>
            <% else%>
              <li><%= link_to "Login", login_path, class: 'list-group-item' %></li>
              <li><%= link_to "Sign Up", signup_path, class: 'list-group-item'%></li>
            <% end %>
        </ul>
        -->
          <ul class="nav nav-pills nav-stacked">
           <li><%= link_to "Articles" ,articles_path%></li>
            <li><%= link_to "Users", users_path%> </li>
            <li><%= link_to 'Add new Article',new_article_path %></li>
             <!--Log in -->
            <!--Log out -->
            <%if loged_in? %>
            <li><%= link_to "Logout", logout_path, method: :delete %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <%= "(*Admin)" if current_user.admin? %> <span class="caret"></span></a>
            </li>
            <% else%>
              <li><%= link_to "Login", login_path %></li>
              <li><%= link_to "Sign Up", signup_path%></li>
            <% end %>
          </ul>
      </div>
      </div>
  </div>
  <div class="col-xs-9 part2">
    <h2 class="text-center">Welocome TO <strong>NewsMap</strong> Articles Blog</h2>
     <%= render 'layouts/messges' %>
  </div>